name: On Pull Request (main)

on:
  pull_request:
    branches:
      - main

jobs:
  test:
    name: Run Tests
    uses: ./.github/workflows/callable-test.yml
    with:
      with_coverage: true
    secrets:
      machine_account_token: ${{ secrets.MACHINE_ACCOUNT_TOKEN }}
